### PR TITLE
 Revision: 34305

### PR DESCRIPTION
**Pull request by PhillipsPaull**
PMD线程机制重构

pmd和net重构，阶段1 - background task增加reuseEDU的接口，对于不参reuse的需要销毁

### CODE REVIEW

**Comment by PhillipsPaull** [comment]
代码提交（主干） 

Revision: 34288 

Date: 2018年2月11日 12:19:20 
Message: 
3031 pmd和net重构，阶段1( fix compile warning ) 
---- 
Modified : /trunk/SequoiaDB/engine/pmd/pmdEDUMgr.cpp 

Revision: 34287 

Date: 2018年2月11日 12:04:28 
Message: 
3031 pmd和net重构，阶段1 
---- 
Modified : /trunk/SequoiaDB/engine/include/pmd.hpp 
Modified : /trunk/SequoiaDB/engine/include/sdbInterface.hpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmdEDUMgr.cpp 

Revision: 34286 
Author: xujianhui 
Date: 2018年2月11日 11:05:33 
Message: 
SEQUOIADBMAINSTREAM-3031 pmd和net重构，阶段1 
---- 
Modified : /trunk/SequoiaDB/engine/SConscript 
Modified : /trunk/SequoiaDB/engine/SConscriptFmp 
Modified : /trunk/SequoiaDB/engine/SConscriptTool 
Modified : /trunk/SequoiaDB/engine/cat/catalogueCB.cpp 
Modified : /trunk/SequoiaDB/engine/cls/clsMgr.cpp 
Modified : /trunk/SequoiaDB/engine/cls/clsReplBucket.cpp 
Modified : /trunk/SequoiaDB/engine/cls/clsReplicateSet.cpp 
Modified : /trunk/SequoiaDB/engine/cls/clsShardMgr.cpp 
Modified : /trunk/SequoiaDB/engine/cls/clsStorageCheckJob.cpp 
Modified : /trunk/SequoiaDB/engine/coord/coordCB.cpp 
Modified : /trunk/SequoiaDB/engine/dps/dpsLogWrapper.cpp 
Modified : /trunk/SequoiaDB/engine/fap/mongodb/mongoSession.cpp 
Modified : /trunk/SequoiaDB/engine/include/clsReplicateSet.hpp 
Modified : /trunk/SequoiaDB/engine/include/clsShardMgr.hpp 
Modified : /trunk/SequoiaDB/engine/include/monCB.hpp 
Modified : /trunk/SequoiaDB/engine/include/monEDU.hpp 
Modified : /trunk/SequoiaDB/engine/include/msgDef.h 
Modified : /trunk/SequoiaDB/engine/include/netEventHandler.hpp 
Added : /trunk/SequoiaDB/engine/include/netEventSuit.hpp 
Modified : /trunk/SequoiaDB/engine/include/netFrame.hpp 
Modified : /trunk/SequoiaDB/engine/include/netRouteAgent.hpp 
Modified : /trunk/SequoiaDB/engine/include/netTimer.hpp 
Modified : /trunk/SequoiaDB/engine/include/pmd.hpp 
Modified : /trunk/SequoiaDB/engine/include/pmdDef.hpp 
Modified : /trunk/SequoiaDB/engine/include/pmdEDU.hpp 
Deleted : /trunk/SequoiaDB/engine/include/pmdEDUEntryPoint.hpp 
Modified : /trunk/SequoiaDB/engine/include/pmdEDUMgr.hpp 
Added : /trunk/SequoiaDB/engine/include/pmdEntryPoint.hpp 
Modified : /trunk/SequoiaDB/engine/include/pmdOptionsMgr.hpp 
Modified : /trunk/SequoiaDB/engine/include/rtnCB.hpp 
Modified : /trunk/SequoiaDB/engine/include/sdbInterface.hpp 
Modified : /trunk/SequoiaDB/engine/mon/monCB.cpp 
Modified : /trunk/SequoiaDB/engine/mon/monDump.cpp 
Modified : /trunk/SequoiaDB/engine/net/netEventHandler.cpp 
Added : /trunk/SequoiaDB/engine/net/netEventSuit.cpp 
Modified : /trunk/SequoiaDB/engine/net/netFrame.cpp 
Modified : /trunk/SequoiaDB/engine/net/netRouteAgent.cpp 
Modified : /trunk/SequoiaDB/engine/omagent/omagentMgr.cpp 
Modified : /trunk/SequoiaDB/engine/omagent/omagentSession.cpp 
Modified : /trunk/SequoiaDB/engine/omsvc/omManager.cpp 
Modified : /trunk/SequoiaDB/engine/opt/optPlanClearJob.cpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmd.cpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmdAgent.cpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmdAsyncNetEntryPoint.cpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmdAsyncSessionAgent.cpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmdBackgroundJob.cpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmdCBMgrEntryPoint.cpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmdCMMain.cpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmdCluster.cpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmdController.cpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmdDpsTransRollback.cpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmdEDU.cpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmdEDUEntryPoint.cpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmdEDUMgr.cpp 
Added : /trunk/SequoiaDB/engine/pmd/pmdEntryPoint.cpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmdLoadWorker.cpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmdLogArchiveMgr.cpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmdLoggW.cpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmdMain.cpp 
Deleted : /trunk/SequoiaDB/engine/pmd/pmdOMAgentEDUEntryPoint.cpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmdOptionsMgr.cpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmdPreLoader.cpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmdProtocolEntryPoint.cpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmdRestSession.cpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmdRestSvc.cpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmdSession.cpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmdTcpListener.cpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmdWindowsListener.cpp 
Modified : /trunk/SequoiaDB/engine/rtn/rtnCB.cpp 
Modified : /trunk/SequoiaDB/engine/rtn/rtnDictCreatorJob.cpp 
Modified : /trunk/SequoiaDB/engine/rtn/rtnPrefetchJob.cpp 
Modified : /trunk/SequoiaDB/engine/rtn/rtnRemoteMessenger.cpp 
Deleted : /trunk/SequoiaDB/engine/tools/seadapter/pmdSeAdptEDUEntryPoint.cpp 
Modified : /trunk/SequoiaDB/engine/tools/seadapter/seAdptMgr.cpp

**Comment by PhillipsPaull** [comment]
请检视PMD相关的代码

**Comment by PhillipsPaull** [comment]
Revision: 34293 

Date: 2018年2月11日 16:34:35 
Message: 
pmd和net重构，阶段1( 线程回池后，设置其 type 为 unknow ) 
---- 
Modified : /trunk/SequoiaDB/engine/pmd/pmdEDUMgr.cpp

**Comment by JacobMoonP** [comment]
rtnJob的线程被重用导致split无法停止 3271

**Comment by PhillipsPaull** [comment]
Revision: 34305 

Date: 2018年2月12日 17:01:03 
Message: 
3031 pmd和net重构，阶段1 - background task增加reuseEDU的接口，对于不参reuse的需要销毁 
---- 
Modified : /trunk/SequoiaDB/engine/include/clsReplBucket.hpp 
Modified : /trunk/SequoiaDB/engine/include/dmsStorageJob.hpp 
Modified : /trunk/SequoiaDB/engine/include/pmdMemPool.hpp 
Modified : /trunk/SequoiaDB/engine/include/pmdSyncMgr.hpp 
Modified : /trunk/SequoiaDB/engine/include/rtnBackgroundJobBase.hpp 
Modified : /trunk/SequoiaDB/engine/include/rtnDictCreatorJob.hpp 
Modified : /trunk/SequoiaDB/engine/pmd/pmdBackgroundJob.cpp

**Comment by PhillipsPaull** [comment]
Revision: 34306 

Date: 2018年2月12日 19:58:09 
Message: 
3031 pmd和net重构，阶段1 - background task增加reuseEDU的接口，对于不参reuse的需要销毁 
---- 
Modified : /trunk/SequoiaDB/engine/pmd/pmdEDUMgr.cpp

**Comment by JacobMoonP** [comment]
【检视意见】 
1. rtnJob的线程被重用导致split无法停止 3271 

2. _pmdEDUMgr::findAndRemove 

   pmdEDUCB* _pmdEDUMgr::findAndRemove( EDUID eduID ) 
   { 
      pmdEDUCB *cb = NULL ; 
      MAP_EDUCB_IT it ; 

      _latch.get() ; 

      if ( _mapIdles.end() != ( it = _mapIdles.find( cb->getID() ) ) ) <----------此处应使用eduID 
      { 
         cb = it->second ; 
         _mapIdles.erase( it ) ; 
      } 
      else if ( _mapRuns.end() != ( it = _mapRuns.find( cb->getID() ) ) ) <----------此处应使用eduID 
      { 
         cb = it->second ; 
         _mapRuns.erase( it ) ; 
      } 

3. _pmdEDUMgr::createIdleEDU 中 PD_TRACE 使用了错误的函数标签 SDB__PMDEDUMGR_CRTNEWEDU PD_TRACE不对齐 

4. 疑似内存泄露问题：valgrind测试中 netFrame.cpp 130行 _netFrame的构造函数中 _mainSuitPtr( SDB_OSS_NEW netEventSuit( this ) )，但使用的是 boost::shard_ptr 不应该出现此问题，gdb跟踪也发现已调用 netEventSuit 的析构函数 

==25825== 64 bytes in 1 blocks are possibly lost in loss record 13 of 35 
==25825== at 0x4C2CA1E: operator new(unsigned long) (vg_replace_malloc.c:332) 
==25825== by 0xEEFA26: boost::asio::io_service::io_service() (io_service.ipp:40) 
==25825== by 0x15FF992: engine::_netEventSuit::_netEventSuit(engine::_netFrame*) (netEventSuit.cpp:53) 
==25825== by 0x13DB4D9: engine::_netFrame::_netFrame(engine::_netMsgHandler*, engine::_netRoute*) (netFrame.cpp:130) 
==25825== by 0x11806BA: engine::_netRouteAgent::_netRouteAgent(engine::_netMsgHandler*) (netRouteAgent.cpp:45) 
==25825== by 0x125C87C: engine::_clsMgr::_clsMgr() (clsMgr.cpp:519) 
==25825== by 0x126255C: engine::sdbGetClsCB() (clsMgr.cpp:1773) 
==25825== by 0x1037BF2: engine::_pmdController::registerCB(SDB_ROLE) (pmdController.cpp:310) 
==25825== by 0xDCA62C: engine::pmdMasterThreadMain(int, char**) (pmdMain.cpp:252) 
==25825== by 0xDCACD8: main (pmdMain.cpp:362)

**Pull request closed without merging**
