### PR TITLE
Revision: 34337

### PR DESCRIPTION
**Pull request by RobertVannn**
逆向pop所有数据时空闲空间统计错误，导致后续插入数据逻辑 id 不符合预期

【new】【固定集合】插入数据超过32M，逆向pop全部数据，再次插入数据查询预期值错误

【重现步骤】 
1.创建固定集合空间，固定集合 
db.createCS('cs',{Capped:true}).createCL('cl',{Capped:true, Size:1024, Max:10000000, AutoIndexId:false}) 
2.插入十万条数据 
for(i=0;i<100000;i++){db.cs.cl.insert({a:"asjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfk"})}
3.pop所有数据 
db.cs.cl.pop({LogicalID:0,Direction:-1}) 
4.再次插入数据 
db.cs.cl.insert({a:1}) 
Takes 0.000905s. 
db.cs.cl.insert({a:2}) 
Takes 0.000659s. 
5.查询数据 
【预期结果】 
db.cs.cl.find() 
{ 
  "_id": 0, 
  "a": 1 
} 
{ 
  "_id": 56, 
  "a": 2 
} 
【实际结果】 
db.cs.cl.find() 
{ 
  "_id": 0, 
  "a": 1 
} 
{ 
  "_id": 33554396, 
  "a": 2 
} 
【备注】 
问题数据长度为1110，数据长度为1236时则不会出现该情况，其他长度的数据未测试，不知道是否有同样的情况

### CODE REVIEW

**Comment by PatrickCruz122** [comment]
之前为了验证lid字段的正确性，自动化用例大部分使用定长的情况测试，如果跟记录长度相关，需要针对该情况补充测试

**Comment by DebbieMadisonS** [comment]
请安排分析

**Comment by PatrickCruz122** [comment]
自动化用例11779需调整，进行logicalID的比较

**Comment by PhillipsPaull** [comment]
请处理

**Comment by RobertVannn** [comment]
【原因分析】 
对工作块中的空闲空间统计不对，前期代码修改及重构引入该问题。 
在pop块中所有记录的情况下，对于逆向的 pop，需要调整块内的空闲空间值（块内逆向pop出来的空间是可重用的），而代码中缺少了该逻辑，导致逆向pop后，空闲空间没有增加，因此再次向其中插入记录时，会认为空间不够（上面的测试中，插入第二条记录的空间不够），而新分配一个块，这就导致了第二条记录的逻辑 id 发生了跳变（刚好变成第二个块的第一条记录的逻辑 id）。

**Comment by RobertVannn** [comment]
【修改方案】 
在逆向pop 块内所有记录的情况下，增加空闲空间调整逻辑（pop部分记录的逻辑已经存在），即增加上被 pop 记录的总大小。

**Comment by RobertVannn** [comment]
【自验证】 
按原始问题场景验证，通过： 
db.createCS('cs',{Capped:true}).createCL('cl',{Capped:true, Size:1024, Max:10000000, AutoIndexId:false}) 
localhost:11810.cs.cl 
Takes 0.344774s. 
for(i=0;i<100000;i++){db.cs.cl.insert({a:"asjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfkasjdlkjflkdsjfk"})}
Takes 32.762664s. 
db.cs.cl.pop({LogicalID:0,Direction:-1}) 
Takes 0.000948s. 
db.cs.cl.insert({a:1}) 
Takes 0.000755s. 
db.cs.cl.insert({a:2}) 
Takes 0.000716s. 
db.cs.cl.insert({a:3}) 
Takes 0.000610s. 
db.cs.cl.find() 
{ 
  "_id": 0, 
  "a": 1 
} 
{ 
  "_id": 56, 
  "a": 2 
} 
{ 
  "_id": 112, 
  "a": 3 
} 
Return 3 row(s). 
Takes 0.002141s.

**Comment by RobertVannn** [comment]
【提交记录】 
Revision: 34337 

Date: 2018年2月22日 13:29:47 
Message: 
3254 3248 逆向pop所有数据时空闲空间统计错误，导致后续插入数据逻辑 id 不符合预期 

Modified : /trunk/SequoiaDB/engine/dms/dmsStorageDataCapped.cpp

**Comment by RobertVannn** [comment]
检查项---------------------------------------------------------结论（NA/N/Y） 

修改代码是否全部提交SVN主干和分支版本 
且符合代码规范--------------------------------------------Y 
是否用例全部通过-----------------------------------------Y 
修改代码是否通过检视------------------------------------提交检视 
资料是否变更-----------------------------------------------NA 
接口是否变更-----------------------------------------------NA 
相关驱动是否变更或添加---------------------------------NA 
是否保持向前兼容------------------------------------------NA 
是否影响安装部署和监控---------------------------------NA 
是否对影响性能--------------------------------------------NA 
sdb shell帮助信息是否更新------------------------------NA

**Comment by RobertVannn** [comment]
已修改，请检视

**Comment by PhillipsPaull** [comment]
请安排测试

**Comment by DebbieMadisonS** [comment]
请验证

**Comment by BettyFrancesZ** [comment]
【验证结果】：验证问题已经解决，请检视 

【回归版本】 
SequoiaDB shell version: 2.9 
Release: 34625 
2018-03-07-00.38.02(Enterprise-Debug) 
【验证步骤】 
1.创建固定集合 
2.插入数据 
3.pop记录，块内记录覆盖：块头、块中、块尾，方向覆盖：前向、后向，检查数据正确 
4.再次插入记录并查询，记录长度覆盖：比之前的记录长、比之前的记录短，检查数据正确 
【测试用例】 
seqDB-11791:pop一个块内的数据 
自动化用例：pop_11791.js

**Comment by PatrickCruz122** [comment]
自动化用例已上传，检视通过，请关闭

**Pull request merged**
