### PR TITLE
 Revision: 34370

### PR DESCRIPTION
**Pull request by JacobMoonP**
3267 : sdbcm 定时检查在 conf 文件不存在时不把节点端口加入进程守护列表

【new】删除节点后立即重建节点报错-145

【重现步骤】 
1、在数据组中创建节点后删除，删除后立即重建节点 
【预期结果】 
创建节点成功 
【实际结果】 
创建节点失败，报错-145 
【备注】 
CI执行测试用例时抛出的错误 
test_db_branch2.8_sync/202 
日志： 
192.168.30.185:8081/SYNCTEST_G3D3_202.tar.gz 
测试用例： 
branches\sequoiadb_2.8\testcase_new\driver\c\load\reloadConf.cpp

### CODE REVIEW

**Comment by JacobMoonP** [comment]
【日志】 
2018-02-09-10.43.51.268945 Level:EVENT 
PID:32473 TID:3986 
Function:pmdEDUEntryPoint Line:1239 
File:SequoiaDB/engine/pmd/pmdEDU.cpp 
Message: 
Start thread[3986] for EDU[ID:293, type:Agent, Name:] 

2018-02-09-10.43.51.543209 Level:EVENT 
PID:32473 TID:3986 
Function:rmANode Line:1507 
File:SequoiaDB/engine/omagent/omagentNodeMgr.cpp 
Message: 
Remove node[svcname=26000] succeed. 

2018-02-09-10.43.51.543401 Level:EVENT 
PID:32473 TID:32476 
Function:handleSessionClose Line:1194 
File:SequoiaDB/engine/pmd/pmdAsyncSession.cpp 
Message: 
Session[Type:OMAgent,NetID:289,R-TID:2397,R-IP:192.168.28.111,R-Port:49806, handle:289] closed 

2018-02-09-10.43.51.543489 Level:EVENT 
PID:32473 TID:3986 
Function:pmdEDUEntryPoint Line:1399 
File:SequoiaDB/engine/pmd/pmdEDU.cpp 
Message: 
Terminating thread[3986] for EDU[ID:293, Type:Agent, Name: Type:OMAgent,NetID:289,R-TID:2397,R-IP:192.168.28.111,R-Port:49806] 

2018-02-09-10.43.51.582702 Level:ERROR 
PID:32473 TID:32475 
Function:initFromFile Line:2249 
File:SequoiaDB/engine/pmd/pmdOptionsMgr.cpp 
Message: 
Failed to read config from file[/opt/sequoiadb/bin/../conf/local/26000/sdb.conf], rc: -4 

2018-02-09-10.43.51.582775 Level:ERROR 
PID:32473 TID:32475 
Function:addNodeGuard Line:895 
File:SequoiaDB/engine/omagent/omagentNodeMgr.cpp 
Message: 
Extract node[26000]'s config from file[/opt/sequoiadb/bin/../conf/local/26000/sdb.conf] failed, rc: -4 

2018-02-09-10.43.51.588569 Level:ERROR 
PID:32473 TID:32475 
Function:_getCfgFile Line:583 
File:SequoiaDB/engine/omagent/omagentNodeMgr.cpp 
Message: 
Access node[26000]'s cfg file failed, rc: -4 

2018-02-09-10.43.51.588592 Level:ERROR 
PID:32473 TID:32475 
Function:monitorNodes Line:467 
File:SequoiaDB/engine/omagent/omagentNodeMgr.cpp 
Message: 
Failed to get node[26000]'s cfg file: rc: -4 

2018-02-09-10.43.51.999770 Level:EVENT 
PID:32473 TID:32476 
Function:getSession Line:920 
File:SequoiaDB/engine/pmd/pmdAsyncSession.cpp 
Message: 
Create session[Type:OMAgent,NetID:290,R-TID:2397,StartType:2] 

2018-02-09-10.43.51.999888 Level:EVENT 
PID:32473 TID:4008 
Function:pmdEDUEntryPoint Line:1239 
File:SequoiaDB/engine/pmd/pmdEDU.cpp 
Message: 
Start thread[4008] for EDU[ID:294, type:Agent, Name:] 

2018-02-09-10.43.52.000016 Level:EVENT 
PID:32473 TID:32476 
Function:handleSessionClose Line:1194 
File:SequoiaDB/engine/pmd/pmdAsyncSession.cpp 
Message: 
Session[Type:OMAgent,NetID:290,R-TID:2397,R-IP:192.168.28.111,R-Port:49827, handle:290] closed 

2018-02-09-10.43.52.000076 Level:EVENT 
PID:32473 TID:4008 
Function:pmdEDUEntryPoint Line:1399 
File:SequoiaDB/engine/pmd/pmdEDU.cpp 
Message: 
Terminating thread[4008] for EDU[ID:294, Type:Agent, Name: Type:OMAgent,NetID:290,R-TID:2397,R-IP:192.168.28.111,R-Port:49827] 

2018-02-09-10.43.52.003658 Level:EVENT 
PID:32473 TID:32476 
Function:getSession Line:920 
File:SequoiaDB/engine/pmd/pmdAsyncSession.cpp 
Message: 
Create session[Type:OMAgent,NetID:291,R-TID:2397,StartType:2] 

2018-02-09-10.43.52.003735 Level:EVENT 
PID:32473 TID:4009 
Function:pmdEDUEntryPoint Line:1239 
File:SequoiaDB/engine/pmd/pmdEDU.cpp 
Message: 
Start thread[4009] for EDU[ID:295, type:Agent, Name:] 

2018-02-09-10.43.52.003902 Level:ERROR 
PID:32473 TID:4009 
Function:_addANode Line:1187 
File:SequoiaDB/engine/omagent/omagentNodeMgr.cpp 
Message: 
service[26000] node existed 

2018-02-09-10.43.52.003998 Level:ERROR 
PID:32473 TID:4009 
Function:_onNodeMgrReq Line:352 
File:SequoiaDB/engine/omagent/omagentSession.cpp 
Message: 
Session[Type:OMAgent,NetID:291,R-TID:2397,R-IP:192.168.28.111,R-Port:49828] process remote code[3] failed, rc: -145

**Comment by JacobMoonP** [comment]
【问题分析】 
omAgentNodeMgr的监视线程隔一段时间启动检查，另外一个线程进行removeNode操作 

监视线程(TID:32475)调用 _omAgentNodeMgr::watchManualNodes() 
监视线程调用omGetSvcListFromConfig() 获取数据节点目录，此时有26000的地址 

操作线程(TID:3986）执行removeNode操作，分别移除了配置文件和_mapDBProcess 

监视线程在watchManualNodes中对每个地址进行处理 
addNodeProcessInfo( vecNodes[i] ) ; ---> 把26000加会_mapDBProcess 
addNodeGuard( vecNodes[i] ) ; ----> 检查是否有配置文件，配置文件已删除，因此出错，但没有移除_mapDBProcess 

监视线程执行monitorNodes 也发现 26000在_mapDBProcess中但没有配置文件，只是设置removing状态，没有移除_mapDBProcess 
                                                          操作线程(TID:4009)开始createNode操作，发现_mapDBProcess中有26000，因此报错-145

**Comment by DebbieMadisonS** [comment]
请安排分析

**Comment by PhillipsPaull** [comment]
定时会在 void _omAgentNodeMgr::monitorNodes() 中将上述的节点标识为 OMNODE_REMOVING， 
同时，会定时执行 cleanDeadNodes， 清除 OMNODE_REMOVING 的节点信息。 

因此，上述冲突的情况经过一定的时间可以自行恢复。

请参考上述备注分析是否为问题。

**Comment by JacobMoonP** [comment]
【修改方案】 
扩展addNodeProcessInfo()，添加checkConfigFile参数，如果指定checkConfigFile为true则addNodeProcessInfo在_mapLatch内检查conf文件是否存在，如果存在则添加到map中，不存在则不需要添加 

watchManualNodes()->addNodeProcessInfo()分支checkConfigFile为true需要检查 
_addANode()->addNodeProcessInfo()分支checkConfigFile为false不需要检查

【修改方案】 
watchManualNodes() 中对每个候选目录(svcname)所在的桶进行加锁，检查conf文件是否存在，如果存在，则加入nodeGuard和nodeProcessMap；如果不存在 不需要加入nodeGuard和nodeProcessMap

**Comment by JacobMoonP** [comment]
【提交记录】 
Revision: r34370(trunk), r34371(sequoiadb_2.8) 

Date: 2018-02-24 
Message: 
3267 : sdbcm 定时检查在 conf 文件不存在时不把节点端口加入进程守护列表 

M SequoiaDB/engine/omagent/omagentNodeMgr.cpp 
【检验步骤】 
见重现步骤 
【Checklist】 
检查项-----------------------------------------------------结论（NA/N/Y） 

修改代码是否全部提交SVN主干和分支版本 ---------- 
且符合代码规范-------------------------------------------- Y (trunk, sequoiadb_2.8) 
是否用例全部通过----------------------------------------- Y 
是否清淅标明重现步骤----------------------------------- Y 
修改代码是否通过检视----------------------------------- NA 
资料是否变更---------------------------------------------- NA 
接口是否变更---------------------------------------------- NA 
相关驱动是否变更或添加-------------------------------- NA 
是否保持向前兼容----------------------------------------- NA 
是否影响安装部署和监控-------------------------------- NA 
是否对影响性能------------------------------------------- NA 
sdb shell帮助信息是否更新----------------------------- NA

已修改，请检视

**Comment by PhillipsPaull** [comment]
请安排测试

**Pull request merged**
